openapi: 3.0.2
info:
  title: Buzz API
  description: The Easy HIPAA-Secure Communication & Collaboration App For All Who Care♥
  version: '1.1'
  license:
    name: Mobiuso
    url: https://opensource.org/license/mit/
servers:
  - url: https://buzz.skyscape.com/api/v1.1
tags:
  - name: Buzz APIs
    description: APIs for Buzz App
paths:
  /sessions:
    $ref: paths/sessions.yaml
